using System.CodeDom.Compiler;
using System.Collections.Immutable;

namespace Reflexor;

public static class IndentedTextWriterExtensions
{
    public static void WriteProxy(this IndentedTextWriter writer, Proxy proxy)
    {
        writer.WriteLine("// <auto-generated/>");
        writer.WriteLine("#nullable enable");
        if (!string.IsNullOrEmpty(proxy.Namespace))
        {
            writer.WriteLine($"namespace {proxy.Namespace}");
            writer.WriteLine("{");
            writer.Indent++;
        }

        writer.WriteDeclaration(proxy.Name, "struct", proxy.Modifiers);
        if (proxy.GenericTypes.Length > 0)
        {
            writer.Write("<");
            writer.Write(string.Join(", ", proxy.GenericTypes));
            writer.Write(">");
        }
        writer.WriteLine();
        writer.WriteLine("{");
        writer.Indent++;

        writer.WriteInstanceMembers(proxy);

        foreach (var property in proxy.Properties)
        {
            writer.WriteProperty(proxy.TargetType, property);
            writer.WriteLine();
        }

        foreach (var method in proxy.Methods)
        {
            writer.WriteMethod(proxy.TargetType, method);
            writer.WriteLine();
        }

#if DECLARE_IMPLICIT_CONVERSION // Replace with csproj property
        writer.WriteLine($"public static implicit operator {proxy.Name}({proxy.TargetType} target) => new {proxy.Name}(target);");
        writer.WriteLine();
#endif

        writer.Indent--;
        writer.WriteLine("}");

        if (!string.IsNullOrEmpty(proxy.Namespace))
        {
            writer.Indent--;
            writer.WriteLine("}");
        }
        writer.WriteLine("#nullable restore");
    }

    public static void WriteInstanceMembers(this IndentedTextWriter writer, Proxy proxy)
    {
        if (!proxy.Modifiers.HasFlag(Modifiers.Static))
        {
            writer.WriteLine($"private readonly {proxy.TargetType} _target;");
            writer.WriteLine();

            writer.WriteLine($"public {proxy.Name}({proxy.TargetType} target)");
            writer.WriteLine("{");
            writer.Indent++;
            writer.WriteLine("_target = target ?? throw new System.ArgumentNullException(nameof(target));");
            writer.Indent--;
            writer.WriteLine("}");
            writer.WriteLine();

            writer.WriteLine("private readonly void ThrowInvalidOperationIfNotInitialized()");
            writer.WriteLine("{");
            writer.Indent++;
            writer.WriteLine("if (_target is null)");
            writer.WriteLine("{");
            writer.Indent++;
            writer.WriteLine($"throw new global::System.InvalidOperationException(\"Proxy for '{proxy.TargetType[8..]}' is uninitialized\");");
            writer.Indent--;
            writer.WriteLine("}");
            writer.Indent--;
            writer.WriteLine("}");
            writer.WriteLine();
        }
    }

    private static void WriteDeclaration(this IndentedTextWriter writer, string name, string type, Modifiers modifiers)
    {
        writer.Write("public ");
        if (modifiers.HasFlag(Modifiers.Static))
            writer.Write("static ");
        if (modifiers.HasFlag(Modifiers.Override))
            writer.Write("override ");
        if (modifiers.HasFlag(Modifiers.ReadOnly))
            writer.Write("readonly ");
        if (modifiers.HasFlag(Modifiers.Unsafe))
            writer.Write("unsafe ");
        if (modifiers.HasFlag(Modifiers.RefStruct))
            writer.Write("ref ");
        if (modifiers.HasFlag(Modifiers.Partial))
            writer.Write("partial ");
        if (modifiers.HasFlag(Modifiers.Ref))
            writer.Write("ref ");
        if (modifiers.HasFlag(Modifiers.RefReadOnly))
            writer.Write("ref readonly ");
        writer.Write(type);
        writer.Write(" ");
        writer.Write(name);
    }

    public static void WriteProperty(this IndentedTextWriter writer, string targetType, Property property)
    {
        var target = property.Modifiers.HasFlag(Modifiers.Static) ? "null!" : "_target";

        var accessorKind = property.Modifiers.HasFlag(Modifiers.Static)
            ? "global::System.Runtime.CompilerServices.UnsafeAccessorKind.StaticMethod"
            : "global::System.Runtime.CompilerServices.UnsafeAccessorKind.Method";

        writer.WriteDeclaration(property.Name, property.Type, property.Modifiers | (!property.Modifiers.HasFlag(Modifiers.Static) ? Modifiers.ReadOnly : Modifiers.None));
        writer.WriteLine();

        writer.WriteLine("{");
        writer.Indent++;

        writer.WriteLine("get");
        writer.WriteLine("{");
        writer.Indent++;
        if (!property.Modifiers.HasFlag(Modifiers.Static))
        {
            writer.WriteLine("ThrowInvalidOperationIfNotInitialized();");
        }
        writer.WriteLine($"return Get{property.Name}({target});");
        writer.WriteLine();
        writer.WriteLine($"[global::System.Runtime.CompilerServices.UnsafeAccessor({accessorKind}, Name = \"get_{property.Name}\")]");
        writer.WriteLine($"extern static {property.Type} Get{property.Name}({targetType} target);");
        writer.Indent--;
        writer.WriteLine("}");

        if (!property.Modifiers.HasFlag(Modifiers.ReadOnly))
        {
            writer.WriteLine();
            writer.WriteLine("set");
            writer.WriteLine("{");
            writer.Indent++;
            if (!property.Modifiers.HasFlag(Modifiers.Static))
            {
                writer.WriteLine("ThrowInvalidOperationIfNotInitialized();");
            }
            writer.WriteLine($"Set{property.Name}({target}, value);");
            writer.WriteLine();
            writer.WriteLine($"[global::System.Runtime.CompilerServices.UnsafeAccessor({accessorKind}, Name = \"set_{property.Name}\")]");
            writer.WriteLine($"extern static void Set{property.Name}({targetType} target, {property.Type} value);");
            writer.Indent--;
            writer.WriteLine("}");
        }

        writer.Indent--;
        writer.WriteLine("}");
    }

    public static void WriteMethod(this IndentedTextWriter writer, string targetType, Method method)
    {
        writer.WriteDeclaration(method.Name, method.ReturnType, method.Modifiers | (IsOverride(method) ? Modifiers.Override : Modifiers.None));
        if (method.GenericTypes.Length > 0)
        {
            writer.Write("<");
            writer.Write(string.Join(", ", method.GenericTypes.Select(x => x.Name)));
            writer.Write(">");
        }
        writer.Write("(");
        writer.WriteCommaSeparatedList(method.Parameters, prependComma: false, (writer, parameter) =>
        {
            writer.Write(parameter.Ref);
            writer.Write(parameter.Type);
            writer.Write(" ");
            writer.Write(parameter.Name);
        });
        writer.WriteLine(")");
        if (method.GenericTypes.Length > 0)
        {
            writer.Indent++;
            foreach (var genericType in method.GenericTypes)
            {
                if (genericType.Constraints.Length > 0)
                {
                    writer.Write("where ");
                    writer.Write(genericType.Name);
                    writer.Write(" : ");
                    writer.WriteCommaSeparatedList(genericType.Constraints, prependComma: false, (writer, constraint) =>
                    {
                        writer.Write(constraint);
                    });
                    writer.WriteLine();
                }
            }
            writer.Indent--;
        }
        writer.WriteLine("{");
        writer.Indent++;
        if (method.ReturnType is not "void")
            writer.Write("return ");
        var target = method.Modifiers.HasFlag(Modifiers.Static) ? "null!" : "_target";
        writer.Write($"Call{method.Name}({target}");
        writer.WriteCommaSeparatedList(method.Parameters, prependComma: true, static (writer, argument) =>
        {
            writer.Write(argument.Ref);
            writer.Write(argument.Name);
        });
        writer.WriteLine(");");
        writer.WriteLine();
        writer.WriteLine($"[global::System.Runtime.CompilerServices.UnsafeAccessor(global::System.Runtime.CompilerServices.UnsafeAccessorKind.Method, Name = \"{method.Name}\")]");
        writer.Write($"extern static {method.ReturnType} Call{method.Name}({targetType} target");
        writer.WriteCommaSeparatedList(method.Parameters, prependComma: true, (writer, parameter) =>
        {
            writer.Write(parameter.Ref);
            writer.Write(parameter.Type);
            writer.Write(" ");
            writer.Write(parameter.Name);
        });
        writer.WriteLine(");");
        writer.Indent--;
        writer.WriteLine("}");

        static bool IsOverride(Method method)
        {
            return method.Name switch
            {
                nameof(ToString) => method.ReturnType is "string" && method.Parameters is [],
                nameof(Equals) => method.ReturnType is "bool" && method.Parameters is [{ Type: "object" }],
                nameof(GetHashCode) => method.ReturnType is "int" && method.Parameters is [],
                _ => false,
            };
        }
    }

    public static void WriteCommaSeparatedList<T>(
        this IndentedTextWriter writer,
        ImmutableArray<T> values,
        bool prependComma,
        Action<IndentedTextWriter, T> write)
    {
        var isFirst = !prependComma;
        foreach (var value in values)
        {
            if (!isFirst) writer.Write(", ");
            else isFirst = false;

            write(writer, value);
        }
    }
}
