using System.Collections.Immutable;
using Microsoft.CodeAnalysis;

namespace Reflexor;

public static class ProxyWriter
{
    extension(ref IndentedStringBuilder writer)
    {
        public void WriteProxy(Proxy proxy)
        {
            writer.WriteLine("// <auto-generated/>");
            writer.WriteLine("#nullable enable");

            if (!string.IsNullOrEmpty(proxy.Namespace))
            {
                writer.Write("namespace ");
                writer.WriteLine(proxy.Namespace);
                writer.WriteLine("{");
                writer.Indent++;
            }

            writer.WriteProxyDeclaration(proxy);
            writer.WriteLine();
            writer.WriteGenericConstraints(proxy.GenericTypes);
            writer.WriteLine("{");
            writer.Indent++;

            writer.WriteInstanceMembers(proxy);

            foreach (var property in proxy.Properties)
            {
                writer.WriteProperty(proxy, property);
                writer.WriteLine();
            }

            foreach (var method in proxy.Methods)
            {
                writer.WriteMethod(proxy, method);
                writer.WriteLine();
            }

            if (!proxy.IsStatic)
            {
                writer.Write("public static implicit operator ");
                writer.Write(proxy.Name);
                writer.WriteGenericTypeArguments(proxy.GenericTypes);
                writer.Write("(");
                writer.Write(proxy.TargetType);
                writer.Write(" target) => new ");
                writer.Write(proxy.Name);
                writer.WriteGenericTypeArguments(proxy.GenericTypes);
                writer.WriteLine("(target);");
                writer.WriteLine();
            }

            writer.Indent--;
            writer.WriteLine("}");

            if (!proxy.IsStatic)
            {
                writer.WriteLine();
                writer.WriteMutateExtensions(proxy);
            }

            if (!string.IsNullOrEmpty(proxy.Namespace))
            {
                writer.Indent--;
                writer.WriteLine("}");
            }

            writer.WriteLine("#nullable restore");
        }

        private void WriteProxyDeclaration(Proxy proxy)
        {
            writer.WriteAccessibility(proxy);
            writer.Write(" ");

            if (proxy.IsStatic)
            {
                writer.Write("static ");
            }

            if (proxy.IsRefLike)
            {
                writer.Write("ref ");
            }

            writer.Write("partial ");
            writer.Write(proxy.IsStatic ? "class " : "struct ");
            writer.Write(proxy.Name);
            writer.WriteGenericTypeArguments(proxy.GenericTypes);
        }

        private void WriteInstanceMembers(Proxy proxy)
        {
            if (proxy.IsStatic)
            {
                return;
            }

            writer.Write("private readonly ");
            writer.Write(proxy.TargetType);
            writer.WriteLine(" _target;");
            writer.WriteLine();

            writer.Write("public ");
            writer.Write(proxy.Name);
            writer.Write("(");
            writer.Write(proxy.TargetType);
            writer.WriteLine(" target)");
            writer.WriteLine("{");
            writer.Indent++;
            writer.WriteLine("_target = target ?? throw new System.ArgumentNullException(nameof(target));");
            writer.Indent--;
            writer.WriteLine("}");
            writer.WriteLine();

            writer.WriteLine("private readonly void ThrowInvalidOperationIfNotInitialized()");
            writer.WriteLine("{");
            writer.Indent++;
            writer.WriteLine("if (_target is null)");
            writer.WriteLine("{");
            writer.Indent++;
            writer.Write("throw new global::System.InvalidOperationException(\"Proxy for '");
            writer.Write(proxy.DisplayTargetType);
            writer.WriteLine("' is uninitialized\");");
            writer.Indent--;
            writer.WriteLine("}");
            writer.Indent--;
            writer.WriteLine("}");
            writer.WriteLine();
        }

        private void WriteProperty(Proxy proxy, Property property)
        {
            writer.Write("public ");
            writer.Write(property.IsStatic ? "static " : "readonly ");
            if (property.IsUnsafe)
            {
                writer.Write("unsafe ");
            }

            writer.Write(property.Type);
            writer.Write(" ");
            writer.Write(property.Name);
            writer.WriteLine();
            writer.WriteLine("{");
            writer.Indent++;

            writer.WriteLine("get");
            writer.WriteLine("{");
            writer.Indent++;
            writer.WritePropertyGuard(proxy, property);
            writer.Write("return ");
            writer.WriteAccessorCall($"Get{property.Name}", property.IsStatic, [.. ImmutableArray<Parameter>.Empty]);
            writer.WriteLine(";");
            writer.WriteLine();
            writer.WriteUnsafeAccessorAttribute(proxy, $"get_{property.Name}", property.IsStatic);
            writer.Write("extern static ");
            writer.Write(property.Type);
            writer.Write(" ");
            writer.WriteAccessorSignature(proxy, $"Get{property.Name}", property.AccessorTargetType, property.AccessorDisplayTargetType, property.IsStatic, ImmutableArray<Parameter>.Empty);
            writer.WriteLine(";");
            writer.Indent--;
            writer.WriteLine("}");

            if (!property.IsReadOnly)
            {
                writer.WriteLine();
                writer.WriteLine("set");
                writer.WriteLine("{");
                writer.Indent++;
                writer.WritePropertyGuard(proxy, property);
                writer.WriteAccessorCall($"Set{property.Name}", property.IsStatic, [new Parameter("value", property.Type, string.Empty)]);
                writer.WriteLine(";");
                writer.WriteLine();
                writer.WriteUnsafeAccessorAttribute(proxy, $"set_{property.Name}", property.IsStatic);
                writer.Write("extern static void ");
                writer.WriteAccessorSignature(proxy, $"Set{property.Name}", property.AccessorTargetType, property.AccessorDisplayTargetType, property.IsStatic, [new Parameter("value", property.Type, string.Empty)]);
                writer.WriteLine(";");
                writer.Indent--;
                writer.WriteLine("}");
            }

            writer.Indent--;
            writer.WriteLine("}");
        }

        private void WriteMethod(Proxy proxy, Method method)
        {
            writer.Write("public ");
            if (method.IsStatic)
            {
                writer.Write("static ");
            }
            else if (method.IsReadOnly)
            {
                writer.Write("readonly ");
            }

            if (method.IsOverride)
            {
                writer.Write("override ");
            }

            if (method.IsUnsafe)
            {
                writer.Write("unsafe ");
            }

            if (method.ReturnsByRefReadonly)
            {
                writer.Write("ref readonly ");
            }
            else if (method.ReturnsByRef)
            {
                writer.Write("ref ");
            }

            writer.Write(method.ReturnType);
            writer.Write(" ");
            writer.Write(method.Name);
            writer.WriteGenericTypeArguments(method.GenericTypes);
            writer.Write("(");
            writer.WriteCommaSeparatedList(
                method.Parameters,
                prependComma: false,
                static (ref writer, parameter) =>
                {
                    writer.Write(parameter.Ref);
                    writer.Write(parameter.Type);
                    writer.Write(" ");
                    writer.Write(parameter.Name);
                });
            writer.WriteLine(")");
            writer.WriteGenericConstraints(method.GenericTypes);

            writer.WriteLine("{");
            writer.Indent++;

            if (!method.IsStatic)
            {
                writer.WriteLine("ThrowInvalidOperationIfNotInitialized();");
            }

            if (method.ReturnType is not "void")
            {
                writer.Write("return ");
            }

            writer.WriteAccessorCall($"Call{method.Name}", method.IsStatic, method.Parameters);
            writer.WriteLine(";");
            writer.WriteLine();
            writer.WriteUnsafeAccessorAttribute(proxy, method.Name, method.IsStatic);
            writer.Write("extern static ");

            if (method.ReturnsByRefReadonly)
            {
                writer.Write("ref readonly ");
            }
            else if (method.ReturnsByRef)
            {
                writer.Write("ref ");
            }

            writer.Write(method.ReturnType);
            writer.Write(" ");
            writer.WriteAccessorSignature(proxy, $"Call{method.Name}", method.AccessorTargetType, method.AccessorDisplayTargetType, method.IsStatic, method.Parameters);
            writer.WriteLine(";");
            writer.Indent--;
            writer.WriteLine("}");
        }

        private void WritePropertyGuard(Proxy proxy, Property property)
        {
            if (!proxy.IsStatic && !property.IsStatic)
            {
                writer.WriteLine("ThrowInvalidOperationIfNotInitialized();");
            }
        }

        private void WriteAccessorCall(
            string name,
            bool isStaticMember,
            ImmutableArray<Parameter> parameters)
        {
            writer.Write(name);
            writer.Write("(");

            writer.Write(!isStaticMember ? "_target" : "null!");

            foreach (var parameter in parameters)
            {
                writer.Write(", ");
                writer.Write(parameter.Ref);
                writer.Write(parameter.Name);
            }

            writer.Write(")");
        }

        private void WriteAccessorSignature(
            Proxy proxy,
            string name,
            string accessorTargetType,
            string accessorDisplayTargetType,
            bool isStaticMember,
            ImmutableArray<Parameter> parameters)
        {
            writer.Write(name);
            writer.Write("(");
            var wroteParameter = false;

            if (isStaticMember && proxy.IsStatic)
            {
                writer.Write("[global::System.Runtime.CompilerServices.UnsafeAccessorType(\"");
                writer.Write(accessorDisplayTargetType);
                writer.Write("\")] object? target");
                wroteParameter = true;
            }
            else if (!isStaticMember || !proxy.IsStatic)
            {
                writer.Write(accessorTargetType);
                writer.Write(" target");
                wroteParameter = true;
            }

            foreach (var parameter in parameters)
            {
                if (wroteParameter)
                {
                    writer.Write(", ");
                }

                writer.Write(parameter.Ref);
                writer.Write(parameter.Type);
                writer.Write(" ");
                writer.Write(parameter.Name);
                wroteParameter = true;
            }

            writer.Write(")");
        }

        private void WriteMutateExtensions(Proxy proxy)
        {
            writer.WriteAccessibility(proxy);
            writer.Write(" static partial class ");
            writer.Write(proxy.Name);
            writer.WriteLine("Extensions");
            writer.WriteLine("{");
            writer.Indent++;

            writer.Write("public static ");
            writer.Write(proxy.TargetType);
            writer.Write(" Mutate");
            writer.WriteGenericTypeArguments(proxy.GenericTypes);
            writer.Write("(this ");
            writer.Write(proxy.TargetType);
            writer.Write(" target, global::System.Action<");
            writer.Write(proxy.Name);
            writer.WriteGenericTypeArguments(proxy.GenericTypes);
            writer.WriteLine("> mutation)");
            writer.WriteGenericConstraints(proxy.GenericTypes);
            writer.WriteLine("{");
            writer.Indent++;
            writer.WriteLine("if (mutation is null)");
            writer.WriteLine("{");
            writer.Indent++;
            writer.WriteLine("throw new global::System.ArgumentNullException(nameof(mutation));");
            writer.Indent--;
            writer.WriteLine("}");
            writer.WriteLine();
            writer.Write("mutation(new ");
            writer.Write(proxy.Name);
            writer.WriteGenericTypeArguments(proxy.GenericTypes);
            writer.WriteLine("(target));");
            writer.WriteLine("return target;");
            writer.Indent--;
            writer.WriteLine("}");

            writer.Indent--;
            writer.WriteLine("}");
        }

        private void WriteUnsafeAccessorAttribute(Proxy proxy, string methodName, bool isStaticMethod)
        {
            var unsafeAccessorKind = isStaticMethod || proxy.IsStatic
                ? "global::System.Runtime.CompilerServices.UnsafeAccessorKind.StaticMethod"
                : "global::System.Runtime.CompilerServices.UnsafeAccessorKind.Method";

            writer.Write("[global::System.Runtime.CompilerServices.UnsafeAccessor(");
            writer.Write(unsafeAccessorKind);
            writer.Write(", Name = \"");
            writer.Write(methodName);
            writer.WriteLine("\")]");
        }

        private void WriteGenericTypeArguments(ImmutableArray<GenericType> genericTypes)
        {
            if (genericTypes.Length <= 0) return;
            writer.Write("<");
            var isFirst = true;
            foreach (var type in genericTypes)
            {
                if (isFirst) isFirst = false;
                else writer.Write(", ");
                writer.Write(type.Name);
            }

            writer.Write(">");
        }

        private void WriteGenericConstraints(ImmutableArray<GenericType> genericTypes)
        {
            if (genericTypes.Length is 0)
            {
                return;
            }

            writer.Indent++;

            foreach (var genericType in genericTypes.Where(genericType => genericType.Constraints.Length > 0))
            {
                writer.Write("where ");
                writer.Write(genericType.Name);
                writer.Write(" : ");
                writer.WriteCommaSeparatedList(genericType.Constraints, prependComma: false, static (ref writer, constraint) => writer.Write(constraint));
                writer.WriteLine();
            }

            writer.Indent--;
        }

        private void WriteAccessibility(Proxy proxy)
        {
            var accessibility = proxy.Accessibility switch
            {
                Accessibility.NotApplicable => string.Empty,
                Accessibility.Private => "private",
                Accessibility.ProtectedAndInternal => "private protected",
                Accessibility.Protected => "protected",
                Accessibility.Internal => "internal",
                Accessibility.ProtectedOrInternal => "protected internal",
                Accessibility.Public => "public",
                _ => throw new InvalidOperationException($"Unknown accessibility: '{proxy.Accessibility}'")
            };

            writer.Write(accessibility);
        }

        private void WriteCommaSeparatedList<T>(
            ImmutableArray<T> values,
            bool prependComma,
            ActionRef<IndentedStringBuilder, T> write)
        {
            var isFirst = !prependComma;

            foreach (var value in values)
            {
                if (!isFirst)
                {
                    writer.Write(", ");
                }
                else
                {
                    isFirst = false;
                }

                write(ref writer, value);
            }
        }
    }

    private delegate void ActionRef<T1, in T2>(ref T1 arg1, T2 arg2);
}
